run:
	python3 ex5_standalone.py data/b15.gph

runfancy:
	echo "You need to have a running version of python graph-tool installed. If you don't, just 'make run'"
	python3 ex5.py data/b15.gph

runall:
	./runall.sh

