#!/usr/bin/env python3

import sys
from lxml import etree

######### functions #########

def validate(filename_schema, filename_xml):
	with open(filename_schema, 'r') as f:
		schema_root = etree.XML(f.read())
	
	schema = etree.XMLSchema(schema_root)
	xmlparser = etree.XMLParser(schema=schema)
	try:
		with open(filename_xml, 'r') as f:
			etree.fromstring(f.read(), xmlparser)
		return True
	except etree.XMLSchemaError:
		return False

def is_comment(element):
	return type(element) == etree._Comment

def extract_information(filename_xml):
	root = etree.parse(filename_xml).getroot() 
	for gas_day in root:
		if is_comment(gas_day): continue
		shift_hour = int(gas_day.attrib['gasDayStartHourInUTC'])
		for boundary_node in gas_day:
			if is_comment(boundary_node): continue
			for time in boundary_node:
				if is_comment(time): continue
				for elem in time:
					if is_comment(elem): continue
					if elem.tag != '{http://gaslab.zib.de/kwpt/measured}amountOfPower': continue
					print("{0},{1},{2}".format(gas_day.attrib['date'], int(time.attrib['hour'])+shift_hour, elem.attrib['value']))


######### variables #########

filename_schema = "measured-1-1-0.xsd"
filename_xml = "example.measured-1-1-0.xml"

# read filename from commandlineargs
#filename_xml = sys.argv[1]
#filename_schema = sys.argv[2]

######### main program #########

# if validate(filename_schema, filename_xml):
# 	print("Validation successfull")
# else:
# 	print("Validation failed.")

extract_information(filename_xml)

